### PR TITLE
Relates to #87 - loads pathway description from pathways.json.

### PR DESCRIPTION
**Pull request by mmmavis**
just waiting for the actual content to finalize but thought i should have the functionality ready first

@ryanpitts not sure if you have time to review?

### CODE REVIEW

**Comment by ryanpitts** [comment]
Checking right now!

**Comment by ryanpitts** [comment]
This looks good to me -- do we want to wait to merge until there's data in `pathways.json`?

**Comment by mmmavis** [comment]
i wanted to merge this first to make sure things don't break...
what do you think? @ryanpitts

**Comment by mmmavis** [comment]
k @ryanpitts okayed on this. merging it to `gh-pages` now

**Pull request merged**
