### PR TITLE
Update sessions.json

### PR DESCRIPTION
**Pull request by sara-mansouri**
Correcting my session web hyperlinks+ removing my co-facilitator (He will not come.)

### CODE REVIEW

**Comment by ryanpitts** [comment]
Hi Sara -- this data needs to be updated in the schedule spreadsheet rather than directly in the JSON here. Otherwise your changes will be overwritten next time the data gets pulled from the spreadsheet.

**Comment by ryanpitts** [comment]
I've updated the data with your changes in the MozFest schedule spreadsheet, so everything should be OK on next update. Thanks for letting us know!

**Comment by sara-mansouri** [comment]
Hi Ryan, How can I edit schedule spreadsheet?

**Comment by sara-mansouri** [comment]
Great! Thanks Ryan! :+1:

**Pull request closed without merging**
